//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class clientes
{
    public int codigo { get; set; }
    public Nullable<int> codigo_imobiliaria { get; set; }
    public Nullable<sbyte> pessoa_fisica { get; set; }
    public string razao { get; set; }
    public string fantasia { get; set; }
    public string cnpj_cpf { get; set; }
    public string ie_rg { get; set; }
    public string imunicipal { get; set; }
    public string endereco { get; set; }
    public string numero { get; set; }
    public string complemento { get; set; }
    public string bairro { get; set; }
    public string cidade { get; set; }
    public string estado { get; set; }
    public string cep { get; set; }
    public string pais { get; set; }
    public string telefone { get; set; }
    public string celular { get; set; }
    public string nextel { get; set; }
    public Nullable<System.DateTime> cadastro { get; set; }
    public string email { get; set; }
    public string site { get; set; }
    public string observacao { get; set; }
    public string estado_civil { get; set; }
    public Nullable<System.DateTime> nascimento { get; set; }
    public string conjuge_nome { get; set; }
    public string conjuge_rg { get; set; }
    public string conjuge_orgao { get; set; }
    public string conjuge_cpf { get; set; }
    public Nullable<System.DateTime> conjuge_nascimento { get; set; }
    public string conjuge_email { get; set; }
}

public partial class imobiliarias
{
    public int codigo { get; set; }
    public Nullable<sbyte> pessoa_fisica { get; set; }
    public string razao { get; set; }
    public string fantasia { get; set; }
    public string cnpj_cpf { get; set; }
    public string ie_rg { get; set; }
    public string imunicipal { get; set; }
    public string endereco { get; set; }
    public string numero { get; set; }
    public string complemento { get; set; }
    public string bairro { get; set; }
    public string cidade { get; set; }
    public string estado { get; set; }
    public string cep { get; set; }
    public string pais { get; set; }
    public string telefone { get; set; }
    public string celular { get; set; }
    public string nextel { get; set; }
    public Nullable<System.DateTime> cadastro { get; set; }
    public string email { get; set; }
    public string site { get; set; }
    public string observacao { get; set; }
    public Nullable<double> comissao_imobiliaria { get; set; }
}
